### ISSUE TITLE
Issue with compound objects child item 'download pdf' button

### ISSUE THREAD

**Issue by juliastone0729** [uidaholib/digital-collections-template-cb-csv#3]
When you click on the 'Download PDF' button on a child item it jumps back to the compound object page instead of downloading the pdf file (see screenshot)

<img width="885" alt="Screenshot 2023-08-24 at 12 29 03 PM" src="https://github.com/uidaholib/digital-collections-template-cb-csv/assets/123985223/ab726284-b537-46df-bc23-c3e21aca657c">

**Comment by evanwill** [comment]
@juliastone0729 this bug has been fixed in the `main` branch, thanks to spotting it! 
I have updated the branch you were working on by merging in `main`, so you are ready to keep working. If you ever need to update a branch from main, I added the UofI specific docs to ["docs/uidaho/" folder](https://github.com/uidaholib/digital-collections-template-cb-csv/tree/main/docs/uidaho).
